#!/bin/bash
echo "🧪 Quick Test Guide"
echo ""
echo "1. Start the app:"
echo "   npm run dev"
echo ""
echo "2. Open browser:"
echo "   http://localhost:5173"
echo ""
echo "3. Test Solo Training:"
echo "   - Click 'Training Mode'"
echo "   - Complete 10 cycles"
echo "   - Check results screen"
echo ""
echo "4. Test Multiplayer:"
echo "   - Click 'Competition Mode'"
echo "   - Create game (host)"
echo "   - Open new tab, join with game code"
echo "   - Play through 5 cycles"
echo ""
echo "5. Test Features:"
echo "   - Tap wrong color → should see glitch + Razz sound"
echo "   - Complete sequence → should auto-lock"
echo "   - Check neon dark mode UI"
echo "   - Verify 20-second timer per cycle"
echo ""
echo "✅ All features should work as described!"
